# Generated by Django 4.2.7 on 2025-03-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoScrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(unique=True)),
                ('likes', models.IntegerField()),
                ('subscribers', models.TextField(max_length=200)),
                ('channel_name', models.TextField(max_length=300)),
                ('views', models.TextField(max_length=50)),
                ('time_posted', models.TextField(max_length=10)),
            ],
        ),
    ]
