# Generated by Django 4.2.7 on 2025-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_videoscrape_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoscrape',
            name='channel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videoscrape',
            name='time_posted',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videoscrape',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videoscrape',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='videoscrape',
            name='views',
            field=models.CharField(max_length=20),
        ),
    ]
